#log
logging:
  path: .
  file: logs/room.log

# Tomcat
server:
    tomcat:
        port: 8080
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
        connection-timeout: 5000
    context-path: /ff
    ssl:
#         key-store: classpath:dc.atersoft.com.jks
#         key-store-password: qsh9qqa1698h09
#         key-store-type: JKS
         key-store: classpath:xcx.atersoft.com.jks
         key-store-password: 8cgcxa1k2vo6
         key-store-type: JKS
         port: 443

spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    redis:
        open: true  # 是否开启redis缓存
        database: 0
        host: localhost
        port: 16379
        password:      # 密码（默认为空）
        timeout: 6000  # 连接超时时长（毫秒）
        pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 5       # 连接池中的最小空闲连接

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/*/*.xml
    configuration:
            map-underscore-to-camel-case: true
